name: Test Python Scripts and Notebooks

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.py'   # Run workflow for changes in Python files
      - '**/*.ipynb' # Run workflow for changes in Jupyter notebooks
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.py'
      - '**/*.ipynb'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest nbval
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test Selected Python Scripts
      run: |
        pytest path/to/your/scripts_folder/

    - name: Validate Selected Jupyter Notebooks
      run: |
        pytest --nbval path/to/your/notebooks_folder/