name: Spell Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install codespell
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv venv --python=python3.10
          source .venv/bin/activate
          uv pip install codespell

      - name: Run codespell
        run: |
          source .venv/bin/activate
          codespell -L "ocassion,occassion,ot,te,tje" **/*.{txt,md,py,ipynb}
